//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHH.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSanPhamEntities1 : DbContext
    {
        public QLSanPhamEntities1()
            : base("name=QLSanPhamEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DMChatLieu> DMChatLieux { get; set; }
        public virtual DbSet<DMHang> DMHangs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
